### PR TITLE
RT orthonormal

### PR DESCRIPTION
**Pull request by EveCharbie**
I think the link Micakel sent is the right way to do it :) So we need to include https://github.com/martinbis11/polar-decomposition-3x3.

### CODE REVIEW

**Comment by mickaelbegon** [comment]
Have a look here using Eigen3:
https://forum.kde.org/viewtopic.php?f=74&t=111895
https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html

File: src/Utils/Rotation.cpp [hunk 1]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+        utils::Matrix3d Ek;
+        float det, E_one_norm;
+        bool use_svd = false;
+
+        
+        // Mk = mat^T
+        Mk = M.transpose();
+        
+        //M one-norm
+        float M_one_norm = 0.0f;
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:337]: Please use `utils::Scalar` instead of `float` as it is a double precision (10^-15 vs 10^-8 for float) when using Eigen

File: src/Utils/Rotation.cpp [hunk 2]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+        for (int i = 0; i < 3; i++)
+        {
+            float col_abs_sum = fabs(M(i, 0)) + fabs(M(i, 1)) + fabs(M(i, 2));
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:340]: This is okay, but another way to get all the elements of a matrix is to use the block method as such:
`M.block(i, 0, 1, 3)` which would be interpreted as (starting from i^th row, 0^th col, taking 1 element of the row and 3 elements of the col)

Comment (pariterre) [reply src/Utils/Rotation.cpp:340]: Again float should be `utils::Scalar`

File: src/Utils/Rotation.cpp [hunk 3]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+        }
+
+        //M infinity-norm
+        float M_inf_norm = 0.0;
+        for (int i = 0; i < 3; i++)
+        {
+            float row_sum = fabs(M(i, 0)) + fabs(M(i, 1)) + fabs(M(i, 2));
+            if (row_sum > M_inf_norm)
+                M_inf_norm = row_sum;
+        }
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:352]: I think this for loop does the exact same as the one before? Did you mean M(0, i) in this one or the previous?
Also, since they both require i = 0 to 2, they probably can be merge into one for loop

File: src/Utils/Rotation.cpp [hunk 4]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+        float det, E_one_norm;
+        bool use_svd = false;
+
+        
+        // Mk = mat^T
+        Mk = M.transpose();
+        
+        //M one-norm
+        float M_one_norm = 0.0f;
+        for (int i = 0; i < 3; i++)
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:338]: For sake of consistency, use an unsigned int instead of an int. The unsigned int used in biorbd is `size_t`, therefore the for loop should read:
`for (size_t i = 0; i<3; ++i)` 
Note also the ++i instead of i++ which is a tiny tiny tiny bit faster

File: src/Utils/Rotation.cpp [hunk 5]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+            cross_product(&(Mk[0]), &(Mk[3]), &(M_adj_Tk[6]));
+            */
+
+            det = Mk(0, 0) * M_adj_Tk(0, 0) + Mk(0, 1) * M_adj_Tk(0, 1) + Mk(0, 2) * M_adj_Tk(0, 2);
+
+            if( det <= 1e-6 )
+            {
+                use_svd = true;
+                std::cout << "Oups, SVD serait utile!\n";
+                break;
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:373]: Is there a reason not to do svd in the first place?

I am not sure it makes sense to write anything to the console here... But if it make sense, please use:
`utils::Error::warning(false, "message");`

File: src/Utils/Rotation.cpp [hunk 6]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+            }
+
+            if( det == 0.0 )
+            {
+                printf("Warning (polarDecomposition) : zero determinant encountered.\n");
+                break;
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:379]: I feel that this should raise an error if this happens. In any case, printf is a bad idea.
Whether it is just a warning, so you can use `utils::Error::warning(det == 0.0, "message");` or an actual problem, therefore you should raise an error using:
`utils::Error::check(det == 0.0, "message");`

Also note that the check is actually doing the if statement for you. So if you are using the error raising mechanism, you don't even have to enclose it in the if-statement

File: src/Utils/Rotation.cpp [hunk 7]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+
+            for(int i = 0; i < 3; i++)
+            {
+                for(int j = 0; i < 3; j++)
+                    {
+                        Ek(i, j) = Mk(i, j);
+                        Mk(i, j) = g1 * Mk(i, j) + g2 * M_adj_Tk(i, j);
+                        Ek(i, j) -= Mk(i, j);
+                    }
+            }
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:413]: See the comments for the previous for loops, but here, they can't be merged as some operations are performed in between

File: src/Utils/Rotation.cpp [hunk 8]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+
+            //M infinity-norm
+            float M_inf_norm = 0.0;
+            for (int i = 0; i < 3; i++)
+            {
+                float row_sum = fabs(M(i, 0)) + fabs(M(i, 1)) + fabs(M(i, 2));
+                if (row_sum > M_inf_norm)
+                    M_inf_norm = row_sum;
+            }
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:440]: Same comments, but here the definitely seem to be merge. Again, row_sum and col_sum don't seem to differ, which seems odd

File: src/Utils/Rotation.cpp [hunk 9]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+
+        
+        if(use_svd) // && force_rotation
+        {
+            // use the SVD algorithm to compute R
+            utils::Matrix3d Mm = M;
+            utils::Matrix3d Um, Vm;
+            utils::Vector3d lambda;
+            utils::Vector3d lambda_inverse;
+            int modified_SVD = 1;
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:452]: Does this happen ofter that the SVD is needed? Why not using it always? If it does not happen often, maybe a raise before is wiser, I feel the same for det==0.0... The reason is that I feel this happen if the provided matrix behaves badly.. And therefore return what should be the orthonormal matrix of a far-from-being-orthonormal-matrix is giving the rope to the user to hang themselves... But I may be wrong!

File: src/Utils/Rotation.cpp [hunk 10]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+            R = Um * Vm.transpose();
+        }
+        else
+        {
+            // R = Mk^T
+            R = Mk.transpose();
+        }
+
+
+        std::cout << "On s'est rendu, youpi!\n";
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:863]: Please note that the prefered return line in `std::cout` is not `\n` but `std::endl` (just a piece of trivia since this french message is probably going to be removed anyway :P)

File: src/Utils/Rotation.cpp [hunk 11]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
...
+
+        // utils::Matrix3d mat;
 
         utils::Error::check(false,
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:867]: That is my mistake, but since we already know that this should raise an error, `utils::Error::raise("message")` is a more intuitive method to call (instead of `check` which is more designed to validate the first argument, that is, if the first argument is false, it raises an error with the message, but if it is true, it does not)

File: src/Utils/Rotation.cpp [hunk 12]
```diff
@@ -312,15 +312,335 @@ void utils::Rotation::checkUnitary()
 #ifndef SKIP_ASSERT
     double sqrtNorm = static_cast<double>(this->squaredNorm());
     bool checkUnit(fabs(sqrtNorm - 3.) < 1e-4);
-    if (!checkUnit){
-        // Make calulation here
-        utils::Matrix3d mat;
+    if (!checkUnit)
```
Comment (pariterre) [inline src/Utils/Rotation.cpp:315]: This looks good overall, I fell now that we should move this code into the proper class (I can help you with that) and write tests on this (I can help you with that too :) )

Thanks for the amazing work again!

**Review by pariterre — CHANGES_REQUESTED** [review]
So far, so good

File: src/Utils/Rotation.cpp (hunk 5 above)
Comment (EveCharbie) [reply src/Utils/Rotation.cpp:373]: It makes sense for debugging ;p

File: src/Utils/Rotation.cpp [hunk 13]
```diff
@@ -455,89 +454,85 @@ void utils::Rotation::checkUnitary()
...
             int n = 3;
 
             utils::Vector3d e;
-            for (int i = 0; i < n; i++) {
-                for (int j = 0; j < n; j++) {
+            for (size_t i = 0; i < n; ++i) {
+                for (size_t j = 0; j < n; ++j) {
                     V(i, j) = normalEq(i, j);
                 }
             }
```
Comment (pariterre) [inline src/Utils/Rotation.cpp]: This feels the same as `V = normalEq;`?

File: src/Utils/Rotation.cpp [hunk 14]
```diff
@@ -455,89 +454,85 @@ void utils::Rotation::checkUnitary()
...
 
 
             // Symmetric Householder reduction to tridiagonal form. (tred2)
-            for (int j = 0; j < n; j++) {
+            for (size_t j = 0; j < n; ++j) {
                 d(j) = V(n-1, j);
             }
```
Comment (pariterre) [inline src/Utils/Rotation.cpp]: `d = V.block(n-1, 0, 1, n);` ?

Comment (pariterre) [reply src/Utils/Rotation.cpp]: I won't check anymore (I let you), but it feels that every matrix/vector operations were written by hand instead of accessing them directly, which is highly ineffective when using the Eigen library

**Review by pariterre — COMMENTED** [review]
some more comments

File: src/Utils/Rotation.cpp (hunk 9 above)
Comment (EveCharbie) [reply src/Utils/Rotation.cpp:451]: I raised an error. But I am not sure if I agree with you since it might be encountered in the process of finding the right matrix. (not only user defined)

File: src/Utils/Rotation.cpp (hunk 12 above)
Comment (EveCharbie) [reply src/Utils/Rotation.cpp:315]: Indeed, I would appreciate if you could help me with that :)

File: src/Utils/Rotation.cpp (hunk 13 above)
Comment (EveCharbie) [reply src/Utils/Rotation.cpp]: I was afraid of 'pointer effect' XD Sorry you have to babysit my c++!

File: src/Utils/Rotation.cpp [hunk 15]
```diff
@@ -369,42 +369,41 @@ void utils::Rotation::checkUnitary()
             if( det <= 1e-6 )
             {
                 use_svd = true;
-                std::cout << "Oups, SVD serait utile!\n";
                 break;
             }
 
-            if( det == 0.0 )
+            utils::Error::check(det == 0.0, "Warning zero determinant encountered in polar decomposition");
```
[the remark this answers is not in the document]
Comment (EveCharbie) [reply src/Utils/Rotation.cpp]: error: no matching function for call to ‘BiorbdEigen3::utils::Error::warning(BiorbdEigen3::utils::String)’ :(

[the remark this answers is not in the document]
Comment (pariterre) [reply src/Utils/Rotation.cpp]: `utils::Error::warning(condition, "Warning determinant smaller than 1e-6 encountered in polar decomposition"); `
where condition is for instance `det == 0.0`

File: src/Utils/Rotation.cpp (hunk 9 above)
Comment (pariterre) [reply src/Utils/Rotation.cpp:446]: Do you mean for any kind of matrices (not necessarily intended rotation matrix?)

**Comment by pariterre** [comment]
The windows failing bug is fixed in #236 
If you are happy with these changes @EveCharbie  I can already to merge!

**Review by pariterre — APPROVED** [review]
LGTM :)
